name: Python CI
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: ./.github/actions/setup-environment
      - name: Lint with flake8
        run: |
          uv run flake8 --count --show-source --statistics
      - name: Lint with pylint
        run: |
          uv run pylint GenEC --score=yes
          uv run pylint tests --rcfile=tests/.pylintrc --score=yes
      - name: Type check with mypy
        run: |
          uv run mypy .

  unit_tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/setup-environment
      - name: Run unit tests
        run: uv run pytest -m unit --cov=. --cov-append --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit

  integration_tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/setup-environment
      - name: Run integration tests
        run: uv run pytest -m integration --cov=. --cov-append --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration

  system_tests:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.9, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/setup-environment
      - name: Run system tests
        run: uv run pytest -m system --cov=. --cov-append --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: system
